version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      JWT_SECRET: tuSuperSecreto
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: whatsappdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
